---
- name: Git Clone WebStoreAPI Project
  local_action:
    module: git
    repo: https://github.com/sarlindo/poker.git
    dest: /tmp/webstoreapi/poker

- name: get RDS endpoint instance facts
  local_action:
    module: rds
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    command: facts
    instance_name: "{{ webstoreapi_dbinstancename }}"
  register: rds_facts

- name: Set RDS endpoint fact
  set_fact: webstoreapi_endpointhost={{ rds_facts.instance.endpoint }}

# temp for dev settings
- name: Update Django Settings File Template
  local_action:
    module: template
    src: /tmp/webstoreapi/poker/poker/devsettings.py.template 
    dest: /tmp/webstoreapi/poker/poker/settings.py

- name: Archive Project
  local_action:
    module: command tar -zcvf ../poker.tar.gz .
    chdir: /tmp/webstoreapi

- name: Copy over application
  unarchive: src=/tmp/poker.tar.gz dest=/var/www

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes

- name: Update Apache Template and copy over to Apache config
  template:
    src: apiwebstore.conf.j2
    dest: /etc/httpd/conf.d/apiwebstore.conf
  notify: restart httpd
